name: Python CI

on:
  push:
    branches: [ branch-Will ]
  pull_request:
    branches: [ branch-Will ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # 这里指定要测试的平台
        python-version: ['3.10.16']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.16'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: echo "No tests yet"